Anya/create profile for existing user backend
SheCodesAus/2024_a_dynamic_array_back_end pull request #18
Opened 2024-03-30 12:19 UTC by awesomeann

## Describe your changes
1. Added error handling for creating a Profile as unauth user
![image](https://github.com/SheCodesAus/2024_a_dynamic_array_back_end/assets/31050368/5f53981a-029d-407e-8da1-0b44ccc525b1)

2. added a method to check whether the user already has a profile and added an error handling for trying to create a second profile.
![image](https://github.com/SheCodesAus/2024_a_dynamic_array_back_end/assets/31050368/214df763-4568-415b-af26-bd32eaf2e2ff)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

E.g. Do you need a quick look or a thorough assessment?

## Checklist:

- [X] I have performed a self-review of my code
- [X] I have recommended where to start and how to proceed with the review

2024-03-30 14:47 UTC, Lyndallh approved these changes

2024-03-31 01:33 UTC, shayzimm approved these changes

2024-03-31 01:47 UTC, Lyndallh requested changes
There has been another branch merged into DEV since this branch was last merged with DEV. This PR will need to be merged with the latest DEV and pushed again (see instructions on slack)

2024-03-31 03:21 UTC, blakerach1 commented
Hey, for consistency, let's change all of the error dictionaries to include "detail" as the key, instead of "message". I think one of the responses that you've screenshot above are django default... so we may as well go with that approach

2024-03-31 03:22 UTC, blakerach1 requested changes
Can you please update the error response dictionary so that the key is "detail" rather than "message"? I will do the same on mine

2024-03-31 05:27 UTC, awesomeann commented
> There has been another branch merged into DEV since this branch was last merged with DEV. This PR will need to be merged with the latest DEV and pushed again (see instructions on slack)

where do you check that Lindi?

2024-03-31 06:44 UTC, blakerach1 approved these changes

2024-03-31 06:46 UTC, shayzimm requested changes

2024-03-31 06:46 UTC, shayzimm commented on DiversiTech/DiversiTech/settings.py
> +    'True'
Can we change this back to false, pls? :)

2024-03-31 07:28 UTC, shayzimm approved these changes

2024-03-31 07:38 UTC, Lyndallh approved these changes

2024-03-31 07:39 UTC, merged